-- msngr backend
-- Run this only in the NEW dedicated msngr Supabase project.

create schema if not exists private;
create extension if not exists citext with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email extensions.citext not null unique,
  display_name text not null check (char_length(display_name) between 1 and 32),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'direct' check (kind = 'direct'),
  direct_key text unique,
  created_by uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  last_read_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000 and octet_length(body) <= 12000),
  created_at timestamptz not null default now()
);

create index if not exists conversation_members_user_idx
  on public.conversation_members(user_id, conversation_id);

create index if not exists messages_conversation_created_idx
  on public.messages(conversation_id, created_at desc);

create index if not exists messages_sender_created_idx
  on public.messages(sender_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

create or replace function private.is_conversation_member(p_conversation_id uuid, p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversation_members cm
    where cm.conversation_id = p_conversation_id
      and cm.user_id = p_user_id
  );
$$;

create or replace function private.users_share_conversation(p_user_a uuid, p_user_b uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.conversation_members a
    join public.conversation_members b
      on b.conversation_id = a.conversation_id
    where a.user_id = p_user_a
      and b.user_id = p_user_b
  );
$$;

revoke all on function private.is_conversation_member(uuid, uuid) from public;
revoke all on function private.users_share_conversation(uuid, uuid) from public;
grant execute on function private.is_conversation_member(uuid, uuid) to authenticated;
grant execute on function private.users_share_conversation(uuid, uuid) to authenticated;

drop policy if exists "profiles_select_shared" on public.profiles;
create policy "profiles_select_shared"
on public.profiles for select
to authenticated
using (
  id = (select auth.uid())
  or private.users_share_conversation((select auth.uid()), id)
);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles for insert
to authenticated
with check (
  id = (select auth.uid())
  and lower(email::text) = lower((select auth.jwt() ->> 'email'))
);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (
  id = (select auth.uid())
  and lower(email::text) = lower((select auth.jwt() ->> 'email'))
);

drop policy if exists "conversations_select_member" on public.conversations;
create policy "conversations_select_member"
on public.conversations for select
to authenticated
using (private.is_conversation_member(id, (select auth.uid())));

drop policy if exists "members_select_conversation" on public.conversation_members;
create policy "members_select_conversation"
on public.conversation_members for select
to authenticated
using (private.is_conversation_member(conversation_id, (select auth.uid())));

drop policy if exists "members_update_self" on public.conversation_members;
create policy "members_update_self"
on public.conversation_members for update
to authenticated
using (
  user_id = (select auth.uid())
  and private.is_conversation_member(conversation_id, (select auth.uid()))
)
with check (
  user_id = (select auth.uid())
  and private.is_conversation_member(conversation_id, (select auth.uid()))
);

drop policy if exists "messages_select_member" on public.messages;
create policy "messages_select_member"
on public.messages for select
to authenticated
using (private.is_conversation_member(conversation_id, (select auth.uid())));

grant select, insert, update on public.profiles to authenticated;
grant select on public.conversations to authenticated;
grant select, update on public.conversation_members to authenticated;
grant select on public.messages to authenticated;

create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(id, email, display_name)
  values (
    new.id,
    new.email,
    left(coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), split_part(new.email, '@', 1), 'User'), 32)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function private.handle_new_user() from public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function private.handle_new_user();

create or replace function public.start_direct_conversation(target_email text)
returns table (
  conversation_id uuid,
  other_user_id uuid,
  display_name text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  target_user_id uuid;
  target_name text;
  key_value text;
  conversation_value uuid;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  select p.id, p.display_name
    into target_user_id, target_name
  from public.profiles p
  where lower(p.email::text) = lower(trim(target_email))
  limit 1;

  if target_user_id is null then
    raise exception 'No account found with that email';
  end if;

  if target_user_id = current_user_id then
    raise exception 'Choose another account';
  end if;

  key_value :=
    case when current_user_id::text < target_user_id::text
      then current_user_id::text || ':' || target_user_id::text
      else target_user_id::text || ':' || current_user_id::text
    end;

  insert into public.conversations(kind, direct_key, created_by)
  values ('direct', key_value, current_user_id)
  on conflict (direct_key)
  do update set direct_key = excluded.direct_key
  returning id into conversation_value;

  insert into public.conversation_members(conversation_id, user_id)
  values (conversation_value, current_user_id), (conversation_value, target_user_id)
  on conflict do nothing;

  return query
  select conversation_value, target_user_id, target_name;
end;
$$;

revoke all on function public.start_direct_conversation(text) from public, anon;
grant execute on function public.start_direct_conversation(text) to authenticated;

create or replace function public.get_inbox()
returns table (
  conversation_id uuid,
  other_user_id uuid,
  display_name text,
  last_message text,
  last_message_at timestamptz,
  unread_count bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    c.id as conversation_id,
    other.user_id as other_user_id,
    p.display_name,
    lm.body as last_message,
    lm.created_at as last_message_at,
    (
      select count(*)
      from public.messages unread
      where unread.conversation_id = c.id
        and unread.sender_id <> auth.uid()
        and unread.created_at > me.last_read_at
    ) as unread_count
  from public.conversation_members me
  join public.conversations c on c.id = me.conversation_id
  join public.conversation_members other
    on other.conversation_id = c.id
   and other.user_id <> me.user_id
  join public.profiles p on p.id = other.user_id
  left join lateral (
    select m.body, m.created_at
    from public.messages m
    where m.conversation_id = c.id
    order by m.created_at desc
    limit 1
  ) lm on true
  where me.user_id = auth.uid()
  order by coalesce(lm.created_at, c.created_at) desc;
$$;

revoke all on function public.get_inbox() from public, anon;
grant execute on function public.get_inbox() to authenticated;

create or replace function public.send_message(p_conversation_id uuid, p_body text)
returns table (
  id bigint,
  conversation_id uuid,
  sender_id uuid,
  body text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  clean_body text := trim(p_body);
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  if not private.is_conversation_member(p_conversation_id, current_user_id) then
    raise exception 'You are not a member of this conversation';
  end if;

  if clean_body is null or char_length(clean_body) = 0 or char_length(clean_body) > 4000 or octet_length(clean_body) > 12000 then
    raise exception 'Message must be between 1 and 4000 characters';
  end if;

  if (
    select count(*)
    from public.messages recent
    where recent.sender_id = current_user_id
      and recent.created_at > now() - interval '10 seconds'
  ) >= 20 then
    raise exception 'You are sending messages too quickly';
  end if;

  return query
  insert into public.messages(conversation_id, sender_id, body)
  values (p_conversation_id, current_user_id, clean_body)
  returning messages.id, messages.conversation_id, messages.sender_id, messages.body, messages.created_at;
end;
$$;

revoke all on function public.send_message(uuid, text) from public, anon;
grant execute on function public.send_message(uuid, text) to authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
